export enum Especialicacao {
  CLINICA_GERAL = 'CLINICA_GERAL',

  EMFERMAGEM = 'EMFERMAGEM',

  GERIATRIA = 'GERIATRIA',

  GINECOLOGIA = 'GINECOLOGIA',

  OBSTETRICIA = 'OBSTETRICIA',

  NUTRICIONISTA = 'NUTRICIONISTA',

  ONCOLOGIA = 'ONCOLOGIA',

  NEUROLOGIA = 'NEUROLOGIA',

  PEDIATRIA = 'PEDIATRIA',

  PSICOLOGIA = 'PSICOLOGIA',
}
